package com.example.bluetooth;

import com.codename1.system.Lifecycle;
import com.codename1.ui.*;
import com.codename1.ui.events.ActionEvent;
import com.codename1.ui.layouts.*;
import com.codename1.io.*;
import com.codename1.ui.plaf.*;

import java.io.IOException;
import com.codename1.bluetoothle.Bluetooth;

/**
 * This file was generated by <a href="https://www.codenameone.com/">Codename One</a> for the purpose
 * of building native mobile applications using Java.
 */
public class OmronApp1 extends Lifecycle {
    @Override
    public void runApp() {
//        Form hi = new Form("Hi World", BoxLayout.y());
//        Button helloButton = new Button("Hello World");
//        hi.add(helloButton);
//        helloButton.addActionListener(e -> hello());
//        hi.getToolbar().addMaterialCommandToSideMenu("Hello Command",
//        FontImage.MATERIAL_CHECK, 4, e -> hello());
//        hi.show();

        final Bluetooth bt = new Bluetooth();
        Form f = new Form("Bluetooth Demo");
        f.setLayout(new BoxLayout(BoxLayout.Y_AXIS));
        f.add(new Button(new Command("enable bluetooth") {
            @Override
            public void actionPerformed(ActionEvent evt) {
                try {
                    if (!bt.isEnabled()) {
                        bt.enable();
                    }
                    if (!bt.hasPermission()) {
                        bt.requestPermission();
                    }
                } catch (IOException ex) {
                    ex.printStackTrace();
                }
            }
        }));
        f.add(new Button(new Command("initialize") {
            @Override
            public void actionPerformed(ActionEvent evt) {
                try {
                    bt.initialize(true, false, "bluetoothleplugin");
                } catch (IOException ex) {
                    ex.printStackTrace();
                }
            }
        }));

        f.show();
    }

//    private void hello() {
//        Dialog.show("Hello Codename One", "Welcome to Codename One", "OK", null);
//    }

}
